name: Push Asset Change to PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  push-file-change:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update enum
        run: |
          echo "/*This is a modified line*/" >> lib/src/icons/next_flutter_icons.dart
          echo $(ls ${{ github.workspace }}/assets/)

      # Commit all changed files back to the repository
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate icons
