name: Push Asset Enum Change to PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  push-file-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update enum
        run: echo "/*This is a modified line*/" >> lib/src/icons/next_flutter_icons.dart
      
      - name: Commit changes
        run: |
          git config --local user.email "abhi@git.com"
          git config --local user.name "AbhiShake1"
          git commit -am "Add file change via action"
